

#私有索引库
source ‘https://github.com/icpmobile/ICPMSpecs.git’
#CocoaPods 公共索引库
source ‘https://github.com/CocoaPods/Specs.git’



use_frameworks!

platform :ios, '9.0'

target 'HTBaseControlKit_Example' do
  pod 'HTBaseControlKit', :path => '../'

  target 'HTBaseControlKit_Tests' do
    inherit! :search_paths

    
  end
end
